
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeozbaiximbclfymiayw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlb3piYWl4aW1iY2xmeW1pYXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MTA3ODAsImV4cCI6MjA1NDk4Njc4MH0.Mvf9LkJg-IxF-NAHQrhB0-Rn8wanqxbDtg7sPKu-zP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
